package edu.virginia.sde.reviews.model;

/**
 * Represents a UVA course in the Course Reviews application.
 * 
 * This class stores all relevant course information including:
 * - Unique identifier (id)
 * - Subject mnemonic (e.g., CS, MATH, BIOL)
 * - Course number (e.g., 3140, 1110)
 * - Course title
 * - Average rating from reviews
 * 
 * Courses are uniquely identified by the combination of subject, number, and title.
 * This model is used across all scenes that require course information.
 */
public class Course {
    /** Unique identifier for the course, generated by the database */
    private int id;
    
    /** Subject mnemonic, 2-4 letters (e.g., CS, MATH) */
    private String subject;
    
    /** Course number, 4 digits (e.g., 3140, 1110) */
    private int number;
    
    /** Full title of the course */
    private String title;
    
    /** Average rating calculated from all reviews */
    private double averageRating;



    /**
     * Creates a course with a specified ID, subject, number, and title.
     * Typically used when loading an existing course from the database.
     *
     * @param id The database-assigned course ID
     * @param subject The course subject mnemonic
     * @param number The course number
     * @param title The course title
     */
    public Course(int id, String subject, int number, String title) {
        this.id = id;
        this.subject = subject;
        this.number = number;
        this.title = title;
        this.averageRating = 0.0;
    }

    /**
     * Creates a new course with subject, number, and title.
     * The ID is set to -1 to indicate it's not yet stored in the database.
     *
     * @param subject The course subject mnemonic
     * @param number The course number
     * @param title The course title
     */
    public Course(String subject, int number, String title) {
        this(-1, subject, number, title);
    }

    /**
     * Gets the course's ID.
     *
     * @return The course's unique identifier
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the course's ID.
     * Typically called after the course is saved to the database.
     *
     * @param id The database-assigned course ID
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Gets the course's subject mnemonic.
     *
     * @return The subject mnemonic (e.g., CS, MATH)
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the course's subject mnemonic.
     *
     * @param subject The new subject mnemonic
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * Gets the course's number.
     *
     * @return The course number (e.g., 3140, 1110)
     */
    public int getNumber() {
        return number;
    }

    /**
     * Sets the course's number.
     *
     * @param number The new course number
     */
    public void setNumber(int number) {
        this.number = number;
    }

    /**
     * Gets the course's title.
     *
     * @return The course title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the course's title.
     *
     * @param title The new course title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Gets the course's average rating.
     *
     * @return The average rating from all reviews
     */
    public double getAverageRating() {
        return averageRating;
    }

    /**
     * Sets the course's average rating.
     * Typically called after calculating from reviews.
     *
     * @param averageRating The new average rating
     */
    public void setAverageRating(double averageRating) {
        this.averageRating = averageRating;
    }

    /**
     * Returns a string representation of the course in the format "SUBJECT NUMBER: TITLE".
     *
     * @return String representation of the course
     */
    @Override
    public String toString() {
        return subject + " " + number + ": " + title;
    }

    /**
     * Returns the formatted average rating as a string with two decimal places.
     * Returns an empty string if there are no ratings.
     *
     * @return Formatted average rating or empty string
     */
    public String getFormattedAverageRating() {
        if (averageRating == 0.0) {
            return " ";
        }
        return String.format("%.2f", averageRating);
    }
} 