package edu.virginia.sde.reviews.model;

/**
 * Represents a user in the UVA Course Reviews application.
 * 
 * This class stores user information including:
 * - Unique identifier (id)
 * - Username (must be unique in the system)
 * - Password (stored as plain text for simplicity)
 * 
 * The User model is used for authentication and tracking review ownership.
 */
public class User {
    /** Unique identifier for the user, generated by the database */
    private int id;
    
    /** Username for login, must be unique */
    private String username;
    
    /** User's password (stored as plain text) */
    private String password;

    /**
     * Creates a user with a specified ID, username, and password.
     * Typically used when loading an existing user from the database.
     *
     * @param id The database-assigned user ID
     * @param username The user's username
     * @param password The user's password
     */
    public User(int id, String username, String password) {
        this.id = id;
        this.username = username;
        this.password = password;
    }

    /**
     * Creates a new user with username and password.
     * The ID is set to -1 to indicate it's not yet stored in the database.
     *
     * @param username The user's username
     * @param password The user's password
     */
    public User(String username, String password) {
        this(-1, username, password);
    }

    /**
     * Gets the user's ID.
     *
     * @return The user's unique identifier
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the user's ID.
     * Typically called after the user is saved to the database.
     *
     * @param id The database-assigned user ID
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Gets the user's username.
     *
     * @return The user's username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the user's username.
     *
     * @param username The new username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Gets the user's password.
     *
     * @return The user's password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the user's password.
     *
     * @param password The new password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Returns a string representation of the user.
     *
     * @return The user's username
     */
    @Override
    public String toString() {
        return username;
    }
} 